### ISSUE TITLE
crash by effect_triggered and it seems to be by primer inserters

### ISSUE THREAD

**Issue by SourMelion** [SourMelion/RT-Optimized#1]
Error

The mod RTOptimized (0.0.1) caused a non-recoverable error.
Please report this error to the mod author.

Error while running event RTOptimized::on_script_trigger_effect (ID 164)
__RTOptimized__/script/event/effect_triggered.lua:75: attempt to index field '?' (a nil value)
stack traceback:
	__RTOptimized__/script/event/effect_triggered.lua:75: in function <__RTOptimized__/script/event/effect_triggered.lua:8>

**Comment by John-Ivar-Flatmo** [comment]
closing since changes reverted in commit 73c55d8
